// eslint.config.cjs
const js = require('@eslint/js');
const tseslint = require('typescript-eslint');
const react = require('eslint-plugin-react');
const reactNative = require('eslint-plugin-react-native');
const prettier = require('eslint-plugin-prettier');
const prettierConfig = require('eslint-config-prettier');
const reactCompiler = require('eslint-plugin-react-compiler');
const reactDoctor = require('eslint-plugin-react-doctor').default;
const unistyles = require('eslint-plugin-react-native-unistyles');

// Package index only exports `configs`, not `rules` — flat config needs `rules` on the plugin object.
const zustandRulesPlugin = {
  rules: {
    'no-multiple-stores': require('eslint-plugin-zustand-rules/lib/rules/no-multiple-stores'),
    'enforce-slices-when-large-state': require('eslint-plugin-zustand-rules/lib/rules/enforce-slices-when-large-state'),
    'use-store-selectors': require('eslint-plugin-zustand-rules/lib/rules/use-store-selectors'),
    'no-state-mutation': require('eslint-plugin-zustand-rules/lib/rules/no-state-mutation'),
    'enforce-use-setstate': require('eslint-plugin-zustand-rules/lib/rules/enforce-use-setstate'),
    'enforce-state-before-actions': require('eslint-plugin-zustand-rules/lib/rules/enforce-state-before-actions'),
  },
};

module.exports = [
  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    ignores: [
      'node_modules',
      'dist',
      'build',
      'android',
      'ios',
      'scripts',
      'packages',
      // Generated by Expo (web export scratch, types) — not our source.
      '.expo',
      'expo-env.d.ts',
    ],
  },

  // React Compiler rules
  {
    plugins: { 'react-compiler': reactCompiler },
    rules: {
      'react-compiler/react-compiler': 'error',
    },
  },

  // Zustand Rules (plugin entrypoint omits `rules`; we attach rule implementations above)
  {
    plugins: { 'zustand-rules': zustandRulesPlugin },
    rules: {
      // Ensures only one Zustand store is created per module
      'zustand-rules/no-multiple-stores': 'error',
    },
  },

  // React Doctor — recommended + React Native + TanStack Query presets
  reactDoctor.configs.recommended,
  reactDoctor.configs['react-native'],
  reactDoctor.configs['tanstack-query'],
  {
    rules: {
      // FlashList v2+ auto-measures items; estimatedItemSize was removed.
      'react-doctor/rn-list-missing-estimated-item-size': 'off',
      // This rule assumes React Compiler auto-memoizes, so it flags every
      // manual memo/useMemo/useCallback as dead weight. The compiler is NOT
      // enabled here (app.json `experiments` = typedRoutes only; babel.config.js
      // has no babel-plugin-react-compiler), so our manual memoization is
      // load-bearing — it's what keeps text/buttons from re-rendering on theme
      // change (measured: removing it takes a theme switch from 2 re-renders to
      // 27+). Re-enable this rule only if/when React Compiler is turned on.
      'react-doctor/react-compiler-no-manual-memoization': 'off',
    },
  },

  // React Native Unistyles — sort-styles enforced; no-unused-styles disabled because the
  // rule only detects static refs (styles.foo) and false-positives on patterns we use:
  // dynamic keys (styles[variant]) and nested access (styles.selectionColor.color).
  ...unistyles.configs.all,
  {
    rules: {
      'react-native-unistyles/no-unused-styles': 'off',
    },
  },

  // React & React Native rules (kept from your original)
  {
    plugins: { react, 'react-native': reactNative },
    settings: { react: { version: 'detect' } },
    rules: {
      'react/react-in-jsx-scope': 'off',
      'no-undef': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      'no-console': 2,
      'react-native/no-inline-styles': 'error',
      'react/jsx-no-bind': [
        'error',
        {
          allowArrowFunctions: true,
          allowFunctions: false,
          allowBind: false,
          ignoreRefs: true,
        },
      ],
      'react/no-unstable-nested-components': ['error', { allowAsProps: false }],
    },
  },

  // Expo Router route files. Navigation `options` (tabBarIcon, headerRight, …)
  // are render CALLBACKS that React Navigation invokes itself — it never mounts
  // them as a component type, so they can't trigger the remount this rule
  // guards against. `allowAsProps` exists for exactly this API.
  {
    files: ['src/app/**/*.{ts,tsx}'],
    rules: {
      'react/no-unstable-nested-components': ['error', { allowAsProps: true }],
    },
  },

  // Prettier integration
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    plugins: { prettier },
    rules: {
      'prettier/prettier': 'error',
      ...prettierConfig.rules,
    },
  },
];
